# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ktaiapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rktaiapi.proto\x12\x13kt.gigagenie.ai.api\"Z\n\x08reqKtStt\x12\x31\n\x06signal\x18\x01 \x01(\x0b\x32\x1f.kt.gigagenie.ai.api.controlMsgH\x00\x12\x11\n\x07pcmData\x18\x02 \x01(\x0cH\x00\x42\x08\n\x06sttReq\"\x7f\n\x08resKtStt\x12\x31\n\x06signal\x18\x01 \x01(\x0b\x32\x1f.kt.gigagenie.ai.api.controlMsgH\x00\x12\x36\n\tsttResult\x18\x02 \x01(\x0b\x32!.kt.gigagenie.ai.api.sttResultMsgH\x00\x42\x08\n\x06sttRes\"1\n\ncontrolMsg\x12\x0f\n\x07msgType\x18\x01 \x01(\t\x12\x12\n\nmsgPayload\x18\x02 \x01(\t\"N\n\x0csttResultMsg\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tstartTime\x18\x03 \x01(\x02\x12\x0f\n\x07\x65ndTime\x18\x04 \x01(\x02\x32]\n\x07KtAiApi\x12R\n\x0cktSttService\x12\x1d.kt.gigagenie.ai.api.reqKtStt\x1a\x1d.kt.gigagenie.ai.api.resKtStt\"\x00(\x01\x30\x01\x42\x14Z\x12sttRestApi/grpcapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ktaiapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022sttRestApi/grpcapi'
  _REQKTSTT._serialized_start=38
  _REQKTSTT._serialized_end=128
  _RESKTSTT._serialized_start=130
  _RESKTSTT._serialized_end=257
  _CONTROLMSG._serialized_start=259
  _CONTROLMSG._serialized_end=308
  _STTRESULTMSG._serialized_start=310
  _STTRESULTMSG._serialized_end=388
  _KTAIAPI._serialized_start=390
  _KTAIAPI._serialized_end=483
# @@protoc_insertion_point(module_scope)
